site_name: Chip Experiment Docs
site_url: https://uoft-chiplab.github.io/chip-experiment/

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - awesome-pages
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])'

hooks:
  - hooks.py
