site_name: Chip Experiment Docs
site_url: https://chip-experiment-docs.com

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - awesome-pages

